"""empty message

Revision ID: 05480f6a7dd0
Revises: 682d5699aaa6
Create Date: 2024-07-25 13:20:58.434010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05480f6a7dd0'
down_revision: Union[str, None] = '682d5699aaa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bancari', sa.Column('filiale_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bancari', 'filiali', ['filiale_id'], ['id'])
    op.add_column('conti_correnti', sa.Column('filiale_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conti_correnti', 'filiali', ['filiale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conti_correnti', type_='foreignkey')
    op.drop_column('conti_correnti', 'filiale_id')
    op.drop_constraint(None, 'bancari', type_='foreignkey')
    op.drop_column('bancari', 'filiale_id')
    # ### end Alembic commands ###
