"""empty message

Revision ID: 0ddd413bf927
Revises: dd93befd01ef
Create Date: 2024-07-26 08:27:48.952114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ddd413bf927'
down_revision: Union[str, None] = 'dd93befd01ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conti_correnti', sa.Column('iban', sa.String(length=27), nullable=True))
    op.create_unique_constraint(None, 'conti_correnti', ['iban'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conti_correnti', type_='unique')
    op.drop_column('conti_correnti', 'iban')
    # ### end Alembic commands ###
