"""empty message

Revision ID: 2b07683b47cb
Revises: 394a95e83ab1
Create Date: 2024-07-30 13:47:52.114634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b07683b47cb'
down_revision: Union[str, None] = '394a95e83ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prestiti', sa.Column('conto_corrent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prestiti', 'conti_correnti', ['conto_corrent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prestiti', type_='foreignkey')
    op.drop_column('prestiti', 'conto_corrent_id')
    # ### end Alembic commands ###
