"""empty message

Revision ID: 2d8a4e5c0f66
Revises: dd36240c2ee4
Create Date: 2024-08-02 09:39:24.349158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8a4e5c0f66'
down_revision: Union[str, None] = 'dd36240c2ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carte_prepagate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=16), nullable=True),
    sa.Column('scadenza', sa.Date(), nullable=True),
    sa.Column('cvv', sa.String(length=3), nullable=True),
    sa.Column('pin', sa.String(length=4), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('limite_spesa', sa.Float(), nullable=True),
    sa.Column('disabilitata', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.add_column('richieste_carte_prepagate', sa.Column('carta_prepagata_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'richieste_carte_prepagate', 'carte_prepagate', ['carta_prepagata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'richieste_carte_prepagate', type_='foreignkey')
    op.drop_column('richieste_carte_prepagate', 'carta_prepagata_id')
    op.drop_table('carte_prepagate')
    # ### end Alembic commands ###
