"""empty message

Revision ID: 5e452c022091
Revises: 0ddd413bf927
Create Date: 2024-07-26 09:39:18.470244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e452c022091'
down_revision: Union[str, None] = '0ddd413bf927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storico_direzione',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('direttore_id', sa.Integer(), nullable=True),
    sa.Column('filiale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['direttore_id'], ['direttori.id'], ),
    sa.ForeignKeyConstraint(['filiale_id'], ['filiali.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('storico_direzione')
    # ### end Alembic commands ###
