"""empty message

Revision ID: 6ae597e73359
Revises: 1864ab9d96d5
Create Date: 2024-07-25 14:16:55.697744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae597e73359'
down_revision: Union[str, None] = '1864ab9d96d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('richieste_conti_correnti', sa.Column('bancario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'richieste_conti_correnti', 'bancari', ['bancario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'richieste_conti_correnti', type_='foreignkey')
    op.drop_column('richieste_conti_correnti', 'bancario_id')
    # ### end Alembic commands ###
