"""empty message

Revision ID: 9b3cb6506096
Revises: 2b07683b47cb
Create Date: 2024-07-30 14:31:00.091492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3cb6506096'
down_revision: Union[str, None] = '2b07683b47cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prestiti', sa.Column('direttore_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prestiti', 'direttori', ['direttore_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prestiti', type_='foreignkey')
    op.drop_column('prestiti', 'direttore_id')
    # ### end Alembic commands ###
