"""empty message

Revision ID: a826ec2c3024
Revises: 9b3cb6506096
Create Date: 2024-08-01 09:12:49.063301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a826ec2c3024'
down_revision: Union[str, None] = '9b3cb6506096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conti_correnti', 'saldo',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('filiali', 'saldo',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('garanzie', 'valutazione',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('mutui', 'importo',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('prestiti', 'importo',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transazioni', 'importo',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transazioni', 'importo',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('prestiti', 'importo',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('mutui', 'importo',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('garanzie', 'valutazione',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('filiali', 'saldo',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('conti_correnti', 'saldo',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
