"""empty message

Revision ID: a9423a187fec
Revises: 23f21ad17a7e
Create Date: 2024-07-29 10:31:01.438074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9423a187fec'
down_revision: Union[str, None] = '23f21ad17a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transazioni', sa.Column('descrizione', sa.String(length=256), nullable=True))
    op.add_column('transazioni', sa.Column('causale', sa.String(length=256), nullable=True))
    op.add_column('transazioni', sa.Column('transazione_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transazioni', 'transazioni', ['transazione_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transazioni', type_='foreignkey')
    op.drop_column('transazioni', 'transazione_id')
    op.drop_column('transazioni', 'causale')
    op.drop_column('transazioni', 'descrizione')
    # ### end Alembic commands ###
