"""empty message

Revision ID: dd36240c2ee4
Revises: a826ec2c3024
Create Date: 2024-08-02 09:29:45.893805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd36240c2ee4'
down_revision: Union[str, None] = 'a826ec2c3024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('richieste_carte_prepagate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('data_accettazione', sa.DateTime(), nullable=True),
    sa.Column('accettata', sa.Boolean(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('bancario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bancario_id'], ['bancari.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('richieste_carte_prepagate')
    # ### end Alembic commands ###
