"""empty message

Revision ID: dd93befd01ef
Revises: 6ae597e73359
Create Date: 2024-07-26 07:46:25.506597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd93befd01ef'
down_revision: Union[str, None] = '6ae597e73359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direttori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('nome', sa.String(length=32), nullable=True),
    sa.Column('cognome', sa.String(length=32), nullable=True),
    sa.Column('data_nascita', sa.Date(), nullable=True),
    sa.Column('indirizzo', sa.String(length=64), nullable=True),
    sa.Column('telefono', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice_fiscale'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direttori')
    # ### end Alembic commands ###
