"""empty message

Revision ID: df8feac882ad
Revises: 2d8a4e5c0f66
Create Date: 2024-08-05 08:24:35.209825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8feac882ad'
down_revision: Union[str, None] = '2d8a4e5c0f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transazioni_interne', sa.Column('carta_prepagata_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transazioni_interne', 'carte_prepagate', ['carta_prepagata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transazioni_interne', type_='foreignkey')
    op.drop_column('transazioni_interne', 'carta_prepagata_id')
    # ### end Alembic commands ###
