"""empty message

Revision ID: e163c0cb9307
Revises: 
Create Date: 2024-07-25 10:32:39.619640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e163c0cb9307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clienti', sa.Column('bancario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clienti', 'bancari', ['bancario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clienti', type_='foreignkey')
    op.drop_column('clienti', 'bancario_id')
    # ### end Alembic commands ###
